repos:
    #- repo: https://github.com/PyCQA/isort
    #  rev: 5.12.0
    #  hooks:
    #        - id: isort
    #- repo: https://github.com/psf/black
    #  rev: 23.9.1
    #  hooks:
    #        - id: black

  # Source: https://github.com/astral-sh/ruff-pre-commit
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: 'v0.1.6'
      hooks:
        # Run the linter.
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]

        # Run the formatter.
        - id: ruff-format
