[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py", "test/unit/test_*.py"]
python_classes = ["Test"]
python_functions = ["test"]
testpaths = ["tests"]
addopts = [
    "--import-mode=importlib",
]


[tool.ruff]
line-length = 88
exclude = [
  ".git",
  ".ipynb_checkpoints",
]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
]


# stop issuing ignore warnings on __init__.py
ignore-init-module-imports = true 

[per-file-ignores]
"__init__.py" = ["F401"]
